public inherited sharing class rest_HTTPStatusCodeConstants {
    public static final Integer OK = 200;
    public static final Integer CREATED = 201;
    public static final Integer ACCEPTED = 202;
    public static final Integer NO_CONTENT = 204;
    public static final Integer PARTIAL_CONTENT = 206;
    public static final Integer MULTIPLE_CHOICES = 300;
    public static final Integer MOVED_PERMANENTLY = 301;
    public static final Integer FOUND = 302;
    public static final Integer NOT_MODIFIED = 304;
    public static final Integer BAD_REQUEST = 400;
    public static final Integer UNAUTHORIZED = 401;
    public static final Integer FORBIDDEN = 403;
    public static final Integer NOT_FOUND = 404;
    public static final Integer METHOD_NOT_ALLOWED = 405;
    public static final Integer NOT_ACCEPTABLE = 406;
    public static final Integer CONFLICT = 409;
    public static final Integer GONE = 410;
    public static final Integer PRECONDITION_FAILED = 412;
    public static final Integer REQUEST_ENTITY_TOO_LARGE = 413;
    public static final Integer REQUEST_URI_TOO_LARGE = 414;
    public static final Integer UNSUPPORTED_MEDIA_TYPE = 415;
    public static final Integer EXPECTATION_FAILED = 417;
    public static final Integer INTERNAL_SERVER_ERROR = 500;
    public static final Integer SERVER_UNAVAILABLE = 503;
}